apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mycluster
  region: ap-south-1
nodeGroups:
  - name: ng1
    desiredCapacity: 2
    instancetype: t2.micro
    ssh:
      publicKeyName: sshkey
  - name: ng2
    desiredCapacity: 1
    instancetype: t2.small
    ssh:
      publicKeyName: sshkey
  